.github/workflows/pull_request.yml, .gitmodules, README.md, docker/run.sh, meson.build, scripts/build.sh, scripts/debug.sh, scripts/unit_test.sh, subprojects/magic_enum.wrap
Point at the correct container.
Also, let's see if the CI works now :)
=> docker: fix run.sh script

scripts/build.sh, scripts/debug.sh, scripts/unit_test.sh, src/attack_generation.h, src/bit_board.h, src/board_defs.h, src/engine/move_handling.h, src/engine/tt_hash.h, src/evaluation/evaluator.h, src/evaluation/history_moves.h, src/evaluation/material_scoring.h, src/evaluation/move_scoring.h, src/evaluation/perft.h, src/evaluation/positioning.h, src/evaluation/pv_table.h, src/movement/move_types.h, src/movement/pawns.h, src/uci_handler.h, tests/meson.build, tests/src/test_history_moves.cpp, tests/src/test_killer_moves.cpp, tests/src/test_move_ordering.cpp, tests/src/test_pv_table.cpp, tests/src/test_tt_hash_table.cpp
I've been hunting a search bug for a few days now. I could not get my head around what was actually causing it.
I fixed the evaluator print debugging -> clear that an over/underflow could happen on deeper searches.
The move sorting felt a bit weird, so I added tests for most of my heuristics. In the end I found the little bugger.. it was a copy paste error in the PVTable meaning that we never followed the PV line. Now the search is waay faster.
=> Fix some bugs + some improvements

.github/workflows/nightly.yml, .github/workflows/pull_request.yml, .gitignore, README.md, scripts/clean.sh, scripts/create_release.sh
This commit adds a script to build and pack a release. Also it adds a github workflow to trigger a nightly build; both scheduled automatically but also from a workflow dispatch.
The nightly releases will be tagged as prerelease drafts meaning that they will not polute the "real" releases.
NOTE: this will add the option to decide which branch to build a nightly from. This is a design choice as it will be quite handy to build a nightly from a feature branch etc. Also, it will allow the auto deploy (WIP) to fallback to "regular nightly" after a given period; perfect for testing!
TODO: easy way to turn it on/off if we want a more longterm test done eg.
=> workflows: implement nightly build/release

meson.build
Static linking will bundle the fmt library in our executable. This is faster and more scalable than expecting dynamic linking for our users.
=> fmt: static link

meson.build, meson.options, scripts/create_release.sh, targets/meson.build
When building on the CI it would run with march=native. This meant that the build was optimized for the server building it and not in general optimized for most x86 cpus.
Using the x86-v2 we can build for almost every CPU out there. And it should also be optimized way further.
=> meson: add ci build arch generalization

.github/workflows/create_release.yml
We should use the inputs..
And we should not allow overwriting a release.
=> workflows: fix some create release issues

tests/cute-chess/.gitignore, tests/cute-chess/README.md, tests/cute-chess/config.json.example, tests/cute-chess/run-tournament.sh
This commit adds a new way of testing the engine.
It will run games with a given config and evaluate the performance between the two engines.
It is possible to setup the amount of games, if the test should run SPRT etc.
More info is added to the README.md.
=> tests: add cutechess tournament tests

src/evaluation/evaluator.h, src/evaluation/game_phase.h, src/evaluation/pesto_tables.h, src/evaluation/positioning.h, src/evaluation/static_evaluation.h, src/helpers/game_phases.h, tests/src/test_scoring.cpp
Our current static evaluation (renamed now) does not handle game phases very well. 
We should now be able to control game phase scores in a more dynamic way.
Also the performance from only looping each piece once is quite massive:
```
Score of Meltdown Build vs Meltdown Baseline: 275 - 200 - 281  [0.550] 756
...      Meltdown Build playing White: 156 - 92 - 131  [0.584] 379
...      Meltdown Build playing Black: 119 - 108 - 150  [0.515] 377
...      White vs Black: 264 - 211 - 281  [0.535] 756
Elo difference: 34.6 +/- 19.7, LOS: 100.0 %, DrawRatio: 37.2 %
SPRT: llr 2.96 (100.4%), lbound -2.94, ubound 2.94 - H1 was accepted
```
=> static_evaluation: add extended tapered evaluation + performance improvements

src/bit_board.h, src/engine/move_handling.h, src/evaluation/history_moves.h, src/evaluation/move_ordering.h, src/evaluation/see_swap.h, src/syzygy/syzygy.h
This reverts commit 4448678b1cbd2e3c90ca19eee0be64eeac461f33.
Ran some tests and it seems that this commit causes a severe elo drop.
I did some initial investigations and we try to extract the target from the "from position". This is not the target hence it will not find a piece. Tried to make a hot fix, but I think it's better to revert this for now and fix the issue :)
=> Revert "move_gen: Implement half-search for `getPieceAtSquare`"

src/evaluation/evaluator.h
See each commit for details.
A while ago since we added pruning. About time to collect some easy elo :))
Results speak for themselves:
```
Score of Meltdown Build vs Meltdown Baseline: 130 - 63 - 115  [0.609] 308
Finished game 306 (Meltdown Baseline vs Meltdown Build): * {No result}
Score of Meltdown Build vs Meltdown Baseline: 130 - 63 - 115  [0.609] 308
...      Meltdown Build playing White: 73 - 30 - 52  [0.639] 155
...      Meltdown Build playing Black: 57 - 33 - 63  [0.578] 153
...      White vs Black: 106 - 87 - 115  [0.531] 308
Elo difference: 76.8 +/- 31.0, LOS: 100.0 %, DrawRatio: 37.3 %
SPRT: llr 2.98 (101.1%), lbound -2.94, ubound 2.94 - H1 was accepted
```
=> Add futility and razoring pruning

.github/workflows/create_release.yml, .github/workflows/nightly.yml, .github/workflows/pull_request.yml, README.md, docker/Dockerfile, docker/build.sh, docker/run.sh, meson.build, scripts/build.sh, scripts/ci_build.sh, scripts/create_release.sh, scripts/debug.sh, scripts/get-native-target.sh, src/engine/tt_hash_table.h, targets/windows-gcc-x86-64-v2.txt, targets/windows-gcc-x86-64-v3.txt, targets/windows-native.txt
This commit adds support for windows cross compilation.
* mingw-w64-gcc compiler added to docker file
* windows-x86-64-v2/v3 targets added
* added automatic support for native builds using the build scripts
* updated CI to build windows releases as well
NOTE: changes to tt_hash_table was necessary as compiler complained about mismatching types. Now it should compile for both linux and windows.
DISCLAIMER: I don't have access to windows, so the whole windows shebang is untested. I'm asking some friends if they can try to run it for me before merging.
closes #39 
closes #41
=> targets: add windows cross compilation targets

tests/cute-chess/.gitignore, tests/cute-chess/build-baseline.sh
This commit adds a helper script to build a baseline for testing. You can simply call this script with the branch you want to build from. The script will ensure your current git state is restored etc.
Reasoning: I found myself building main as a baseline and it became annoying to handle that myself. Now we can just call this script and it's automatic.
=> tests: add script to build baseline

src/main.cpp, src/uci_handler.h, version/meson.build, version/version.h.in
This commit adds auto generated author information.
I can't take credits for all the engine work, so I want to make sure
that authors that help contributing to the engine is also praised. Their
name will now be embedded in the engine as a way to show appreciation
for the support and contributions :)
Example: 
```
============================
MELTDOWN          
Chess Engine        
============================
Engine:      Meltdown
Authors:     Run 'authors'
Github:      hansbinderup/meltdown-chess-engine
Version:     0.0.0-dev
Build hash:  f4f959b
Build type:  release
Builtin:     BMI2
authors
186  Hans Binderup
3  Clara Shepherd
```
=> uci_handler: add authors print out

src/board_defs.h, src/engine/move_handling.h, src/evaluation/perft.h, src/helpers/formatters.h, src/main.cpp, src/movegen/move_types.h, src/syzygy/syzygy.h, src/uci_handler.h
This commit adds formatting helpers.
We previously had one formatting helper for "Moves". The formatting library is quite powerful so we might as well use it a little more.
An example of this is generic enum formatting. We can now simply paste an enum into the formatter and it will return the static name of the enum, pretty cool.
=> helpers: add formatting helper

src/parsing/input_parsing.h, src/uci_handler.h, src/uci_options.h
Previously it was quite a pain to add new UCI options. You had to add it manually to the "uci ok string", the debug handle and manually parse all the data.
Now instead, all you have to do is add it to the list and implement the callback.
Adding new types is also easy but requires a bit more work.
This implementation should be better, safer and way faster for new additions.
=> uci_handler: add uci options generalization

src/engine/bench.h, src/evaluation/evaluator.h, src/main.cpp, src/uci_handler.h
This commit adds the option to "bench" the engine. This is a "more or less standardized" way of benchmarking engines.
The positions are used by most engines out there.
We have two ways of running a bench:
From the UCI handler: bench <depth>
From cmd line directly: ./meltdown bench
The latter is necessary for eg. openbench.
=> engine: add bench

src/engine/bench.h
Previously the TT would still be occupied between runs. This meant that running a bench multiple times would generate different results. Also it would mean that bench could be "corrupted" from previous searches etc.
Bench 13598897
=> bench: clear TT between runs

.github/workflows/pull_request.yml, scripts/verify_commit_bench.sh
[Example](https://github.com/hansbinderup/meltdown-chess-engine/actions/runs/14562959813?pr=58) where the commit message contains the wrong bench eg.
See commit message for more details :))
NOTE: for this to work I've enabled a setting for the repo where each branch must be up to date with main before merging. This is necessary for the bench values to reflect the value they'll have when merged to main.
=> Add bench verification to PR checks

src/movegen/move_generation.h, src/parsing/fen_parser.h
The fen parser bug was the one found on the test server:
```
[Event "?"]
[Site "?"]
[Date "2025.04.18"]
[Round "1"]
[White "Meltdown-base"]
[Black "Meltdown-dev"]
[Result "0-1"]
[FEN "r1b1k1nr/p2pp1bp/2p2pp1/q7/2B1P3/3Q4/PPP2PPP/RNB1K2R w KQkq - 0 1"]
[GameDuration "00:00:00"]
[GameEndTime "2025-04-18T12:51:12.831 CEST"]
[GameStartTime "2025-04-18T12:51:12.477 CEST"]
[PlyCount "0"]
[SetUp "1"]
[Termination "illegal move"]
[TimeControl "10.11+0.1"]
{White makes an illegal move: e1g1} 0-1
```
Quite unlikely to happen though, but still, should work.
Also, the attack mask bug *could not* happen in a game - king would be in check after the move. But no reason to generate the move (debug handles would show it as legal move).
=> bugs: fix castling bugs

src/evaluation/evaluator.h
This commit makes the engine aware of the 50 move draw rule. In my previous tests I've seen a lot of draws due to 50 move draw rule. I think it's about time that we teach the engine about this rule to avoid those draws if not necessary.
Initial tests:
```
Score of Meltdown Build vs Meltdown Baseline: 130 - 125 - 145  [0.506] 400
...      Meltdown Build playing White: 72 - 57 - 71  [0.537] 200
...      Meltdown Build playing Black: 58 - 68 - 74  [0.475] 200
...      White vs Black: 140 - 115 - 145  [0.531] 400
Elo difference: 4.3 +/- 27.2, LOS: 62.3 %, DrawRatio: 36.3 %
SPRT: llr -0.0351 (-1.2%), lbound -2.94, ubound 2.94
Player: Meltdown Build
"Draw by 3-fold repetition": 104
"Draw by fifty moves rule": 17
"Draw by insufficient mating material": 22
"Draw by stalemate": 2
"Loss: Black …
```
=> evaluator: add 50 moves draw rule

src/evaluation/evaluator.h
Previously we would enter quiesence search prior to incrementing the search depth for king threat positions.
Instead we should continue our search with increased depth (like we would normally do).
Bench 14371033
[Test results](https://openbench.bunny.beer/test/15/)
=> evaluator: correct king threat search depth

src/engine/bench.h, src/engine/tt_hash_table.h
When resetting the hash table for bench it would result in a nullptr being return from the allocator.
We should not allow setting the table to size 0. We need at least 1mb table, so set a lower limit.
Bench 14238911
=> tt_hash_table: add min size

src/engine/bench.h, src/engine/tt_hash_table.h
Did not return mb.. it returned the size of the table instead.
Bench 14238911
=> tt_hash_table: correct getSizeMb

README.md, meson.build, meson.options, scripts/build.sh
This commit adds the option to build a developer build. We have different optimization levels. We're already running an "optimized" build. BUT, we're still compiling without NDEBUG which has quite a runtime penalty.
NDEBUG should only be used for actual releases though. It's quite a comfort while developing. Therefore add a setting where we can specify developer build settings.
Bench 11349788
NOTE: I'll update the tournament script to build optimized builds. But it requires more than a few changes, so I'll leave that for now
=> meson: add developer-build option

src/evaluation/evaluator.h
Currently we're adding an arbritary time bonus to avoid not having a PV move. This is adding some funky timing issues in ultra bullet where 250ms is extremely long time - compared to how long the search would otherwise search for.
Instead remove this weird time bonus and instead ensure that we at least always search one depth.
Bench 11349788
=> evalutor: correct min search

src/evaluation/evaluator.h, src/evaluation/searcher.h, src/uci_handler.h, tests/src/test_scoring.cpp
Evaluator was getting so large it was becoming unwieldy, so this commit splits it into an evaluator (time control, iterative deepening) and a searcher (search and heuristics).
The searcher's early return on e.g. a stop() call is handled by a separate flag to the evaluator's. This clarifies ownership and looks toward the multi-threading scenario of multiple searchers.
Bench 11349788
=> evaluation: Split evaluator into evaluator+searcher

src/engine/bench.h, src/main.cpp, src/uci_handler.h
Now that we have thread pools we don't need to allocate threads just for a "debug/testing handle".
Instead we can just pass an evaluator and let the consumer have ownership instead.
This has a few extra benefits:
1. No extra threads running
2. Thread count will automatically be updated (no need to pass args etc)
3. Less memory allocated
Bench 11349788
=> bench: pass evaluator instead of self ownning

src/uci_handler.h
Previously the engine name was provided under "id engine". This is incorrect as the engine name should be provided as "id name".
Also added version number to make versioning clear during tournaments.
Bench 11029400
=> uci_handler: correct engine id name

src/engine/move_handling.h, src/engine/tt_hash_table.h, tests/src/test_move_gen_hashing.cpp, tests/src/test_perft.cpp
This commit adds support for prefetching transposition table entries.
One downside of having a larger table is the increased risk of cache misses during lookups. To mitigate this, we issue a prefetch instruction to bring the relevant memory into the cache ahead of time.
Bench 11029400
```
Elo   | 5.52 +- 4.13 (95%)
Conf  | 8.0+0.08s Threads=1 Hash=128MB
Games | N: 10004 W: 3520 L: 3361 D: 3123
Penta | [261, 687, 2977, 786, 291]
https://openbench.bunny.beer/test/85/
```
=> tt_hash_table: add prefetch

src/evaluation/searcher.h
Previously the draw score was "0". This is also theoretically correct. But in terms of pruning it can cause some issues as we might actually find a three fold line that win us the game.
So this is an attempt at reducing the draw blindness towards such lines.
Bench 11044213
```
Elo   | 2.94 +- 9.73 (95%)
Conf  | 8.0+0.08s Threads=1 Hash=8MB
Games | N: 2008 W: 678 L: 661 D: 669
Penta | [51, 179, 546, 158, 70]
https://openbench.bunny.beer/test/87/
```
=> evaluation: add variance to draw score

src/board_defs.h, src/evaluation/evaluator.h, src/uci_handler.h
This commit fixes overflows and incorrect buffer size for searchers.
Prior to this commit it was possible to add "256" threads; uint8_t would overflow and the search result array was limited to 128 (local constant).
Bench 11029400
=> uci_handler: correct threads option

src/uci_handler.h
In the openbench tests I've seen the engine crash every now and then. I noticed that all the crashes happened when we were 400~ ply deep. This lead to me checking the input buffer for overflowing.
Using the follow uci command:
```
position startpos moves e2e4 e7e5 g1f3 b8c6 f1b5 a7a6 b5a4 g8f6 e1g1 f8e7 f3h4 e7f8 h4f3 f8e7 f3h4 e7f8 h4f3 f8e7 f3h4 e7f8 h4f3 f8e7 f3h4 e7f8 h4f3 f8e7 f3h4 e7f8 h4f3 f8e7 f3h4 e7f8 h4f3 f8e7 f3h4 e7f8 h4f3 f8e7 f3h4 e7f8 h4f3 f8e7 f3h4 e7f8 h4f3 f8e7 f3h4 e7f8 h4f3 f8e7 f3h4 e7f8 h4f3 f8e7 f3h4 e7f8 h4f3 f8e7 f3h4 e7f8 h4f3 f8e7 f3h4 e7f8 h4f3 f8e7 f3h4 e7f8 h4f3 f8e7 f3h4 e7f8 h4f3 f8e7 f3h4 e7f8 h4f3 f8e7 f3h4 e7f8 h4f3 f8e7 f3h4 e7f8 h4f3 f8e7 f3h4 e7f8 h4f3 f8e7 f3h4 e7f8 h4f3 f8e7 f3h4 e7f8 h4f3 f8e7 f3h4 e7f8 h4f3 f8e7 f3h4 e7f8 h4f3 f8e7 f3h4 e7f8 h4f3 …
```
=> uci_handler: increase input buffer size to fix crashes

src/engine/move_handling.h, src/engine/tt_hash_table.h, src/evaluation/see_swap.h, src/movegen/move_generation.h, src/movegen/move_types.h, src/movegen/pawns.h, src/syzygy/syzygy.h, tests/src/test_history_moves.cpp, tests/src/test_killer_moves.cpp, tests/src/test_move_vote_map.cpp, tests/src/test_pv_table.cpp, tests/src/test_scoring.cpp, tests/src/test_see_swap.cpp, tests/src/test_tt_hash_table.cpp
We used to store quite a bit of metadata in the moves. For this to work we had to allocate 32bits for each move.
If we move the "piece" meta data to a look-up we can instead half the memory and store almost the same information.
This is beneficial for TT as we'll create 16bits of data that we can use for something else (todo).
Bench 12149207
[Test](https://openbench.bunny.beer/test/106/) is running
=> movegen: scale moves to fit in 16bits instead of 32bit

src/engine/tt_hash_table.h, src/evaluation/score.h, src/evaluation/searcher.h, src/movegen/move_types.h, tests/src/test_tt_hash_table.cpp
As our static evaluation grows in complexity it also grows in time to
compute. Therefore it might be beneficial to add the evaluation to our
last slot in the transpostion table.
This commit adds the possibility to add a lighter entry in our tables.
It will contain no score nor move. Therefore I've also added a term
"noScore" and created a helper to create null moves.
As these "entries" are solely used for evaluation we ofc allow a full
search to be stored over a simple evaluation.
Bench 8688357
Should be merged after #91 
Closes #89 
```
Elo   | 12.82 +- 9.86 (95%)
SPRT  | 8.0+0.08s Threads=1 Hash=128MB
LLR   | 3.14 (-2.94, 2.94) [0.00, 20.00]
Games | N: 2766 W: 942 L: 840 D: 984
Penta | [115, 271, 527, 337, 133] …
```
=> tt: add evaluation to entries

src/bit_board.h, src/evaluation/searcher.h, src/spsa/parameters.h
Previously we would reduce depth with a fixed value when doing null
move pruning. We'd also use a naive depth check.
Instead replace the depth check with an evaluation margin check and
prune based on our current depth.
This allows us to do more fancy tricks in the future as well (improving
heuristics eg.)
Bench 7935208
```
zugswang only:
Elo   | 8.86 +- 6.10 (95%)
LLR   | 2.95 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 3882 W: 1261 L: 1162 D: 1459
Penta | [55, 314, 1125, 371, 76]
https://openbench.bunny.beer/test/199/
combined:
Elo   | 24.81 +- 11.55 (95%)
LLR   | 3.03 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 2160 W: 727 L: 573 D: 860
Penta | [82, 223, 358, 293, 124]
https://openbench.bunny.beer/test/200/
```
=> searcher: depth based NMP | zugzwang check for NMP

.github/workflows/pull_request.yml, src/parsing/input_parsing.h, src/uci_handler.h, src/uci_options.h
1. spin value should be signed (allow negative values)
2. print debug options for spsa values as well
3. input parsing could only return unsigned values
4. the spsa uci options were not hooked up to the uci handler
5. pull request workflow was using the wrong build script
Bench 4297319
=> uci-options: fix spsa bugs

.github/workflows/create_release.yml
Previously the checkout action would do a magic single depth checkout. This meant that all author contributions would be limited to that single commit assigned to the one triggering the action itself.
NOTE: `clean=true` is default, so I removed it
Bench 4397450
=> workflows: fix authors for releases

src/evaluation/static_evaluation.h, src/evaluation/term_methods.h
By using the new macro we can clean up material scoring. This is cleaner and might also be a little more efficient.
Bench 4351729
[Reg test](https://openbench.bunny.beer/test/263/) is running
=> static_evaluation: clean up material scoring

README.md
Meltdown is cpp23 and we no longer provice nightly builds. Also added CCRL link.
Bench 4016654
=> readme: remove deprecated information and add ccrl link

src/core/time_manager.h, src/evaluation/evaluator.h, src/search/searcher.h, src/syzygy/syzygy.h
See each commit :)
```
Syzygy disabled:
Elo   | 11.43 +- 11.31 (95%)
SPRT  | 8.0+0.08s Threads=2 Hash=128MB
LLR   | 1.38 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 1764 W: 486 L: 428 D: 850
Penta | [42, 212, 335, 232, 61]
https://openbench.bunny.beer/test/288/
```
```
Syzygy enabled:
Elo   | 3.75 +- 7.11 (95%)
SPRT  | 8.0+0.08s Threads=2 Hash=128MB
LLR   | 1.05 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 2688 W: 573 L: 544 D: 1571
Penta | [17, 300, 692, 307, 28]
https://openbench.bunny.beer/test/284/
```
=> searcher: improve when stopped | fix syzygy threading bug | fix shutdown memory issue

src/search/searcher.h
This commit adds handling similar to negamax (or actually the same
except no depth is provided):
When qsearch has completed, write the alpha move to transposition table.
Bench 3078472
```
Elo   | 30.54 +- 20.74 (95%)
LLR   | 2.95 (-2.94, 2.94) [0.00, 20.00]
Games | N: 536 W: 171 L: 124 D: 241
Penta | [10, 61, 87, 92, 18]
https://openbench.bunny.beer/test/282/
```
=> searcher: add qsearch tt alpha move write

meson.build
Previously we would only provide the static flags for windows executables.
But as some Linux users with different OS and gcc versions are unable to
run the executables then ensure that we provide a somewhat static bundle.
Bench 4247247
closes #113
=> meson: compile static linux binaries 

src/search/searcher.h
More info about cut-nodes can be found here:
https://www.chessprogramming.org/Node_Types#Cut-Nodes
For now add it to lmr reduction as it's the simplest application.
Bench 3230833
```
Elo   | 2.73 +- 4.62 (95%)
LLR   | 0.60 (-2.94, 2.94) [0.00, 5.00]
Games | N: 11340 W: 3059 L: 2970 D: 5311
Penta | [373, 1386, 2093, 1415, 403]
https://openbench.bunny.beer/test/310/
```
=> searcher: add cut node

src/search/searcher.h
This commit adds initial "improving heuristics".
The improving heuristic is a scalar that can be appended to various other heuristics. Ie search less deep when not improving (not an important positition?) and maybe search deeper when improving (more important position?).
As a start simply append the improving heuristic to LMR where we can reduce the search depth if the position is not improving.
Bench 1678321
```
Elo   | 14.77 +- 7.82 (95%)
Games | N: 4024 W: 1234 L: 1063 D: 1727
Penta | [127, 432, 764, 521, 168]
https://openbench.bunny.beer/test/344/
```
=> searcher: add improving heuristics

src/search/move_picker.h, src/search/pv_table.h, src/search/searcher.h, src/syzygy/syzygy.h, tests/src/test_scoring.cpp
Move generation is currently happening in the searcher, but its only use is to be consumed by the picker.
This commit move the generation to the picker, which also will enable optimizations, e.g. staged move generation.
Bench 2389574
=> move_picker: move generation to picker

src/evaluation/term_methods.h, src/utils/bit_operations.h
See each commit for details
```
Elo   | 0.09 +- 2.80 (95%)
LLR   | 3.02 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 27704 W: 7883 L: 7876 D: 11945
Penta | [847, 3080, 5984, 3101, 840]
https://openbench.bunny.beer/test/343/
```
=> terms: clean up terms | generalize compile time args

src/core/transposition.h
If we already have a move stored (ie a search write and not just a static eval write) then we might as well save that instead of overwriting with a null move.
This should lead to better move ordering.
Bench 1609705
```
Elo   | 38.85 +- 13.12 (95%)
Games | N: 1392 W: 442 L: 287 D: 663
Penta | [25, 141, 254, 206, 70]
https://openbench.bunny.beer/test/392/
```
=> transposition: don't overwrite tt moves

src/search/move_picker.h, src/search/searcher.h
This reverts commit 88e7dcadf66214431991bd4f2f4c518b75023bd4.
Picking the TT move directly led to a race condition in the multi-threaded use case. The gains were small, so we revert the change and focus our interests elsewhere.
Bench 1555918
=> Revert "move_picker: lazily pick TT move"

.github/workflows/create_release.yml, .github/workflows/pull_request.yml, README.md, docker/Dockerfile, docker/build.sh, docker/run.sh, meson.build, scripts/create_release.sh, targets/linux-x86-64-v2.txt, targets/linux-x86-64-v3.txt, targets/windows-gcc-x86-64-v2.txt, targets/windows-x86-64-v2.txt, targets/windows-x86-64-v3.txt
The LLVM toolchain seems to be the golden standard for chess engines. I've conducted a few tests and it's literally insane how much of a difference it makes!
Let's default to clang going forward!
NOTE: I've kept the GCC targets as they might come handy for people trying to compile the engine natively etc.
Bench 2955703
```
Elo   | 24.56 +- 13.61 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 10.00]
Games | N: 1162 W: 348 L: 266 D: 548
Penta | [25, 114, 236, 166, 40]
https://openbench.bunny.beer/test/490/
```
[LTC](https://openbench.bunny.beer/test/493/) is running
=> build: default to llvm toolchain

src/search/searcher.h
Our static evaluation is quite off when we're checked. It's a "lost" position no matter what, so we should reflect that in the evaluation.
The same goes for the "isImproving" - we're not in a better position if we're checked.
This fixes missing mating lines and in general a safer search.
NOTE: we already do the same in qsearch.
Bench 3113053
```
Elo   | 3.78 +- 4.50 (95%)
LLR   | 1.35 (-2.94, 2.94) [0.00, 5.00]
Games | N: 11312 W: 3125 L: 3002 D: 5185
Penta | [350, 1317, 2219, 1400, 370]
https://openbench.bunny.beer/test/496/
```
=> searcher: add `isChecked` to negamax eval

src/core/zobrist_hashing.h, src/search/correction_history.h, src/spsa/parameters.h
Adds "threats" as correction as well.
The threat is basically a bitmask of pieces being attacked which are
being hashed using the same hash algorithm we use for zobrist.
This can corrected for in the same way as the other parameters.
Easy to add, nice little gain :)
Bench 3337853
```
Elo   | 9.03 +- 5.77 (95%)
LLR   | 2.99 (-2.94, 2.94) [0.00, 5.00]
Games | N: 7158 W: 1973 L: 1787 D: 3398
Penta | [216, 845, 1309, 955, 254]
https://openbench.bunny.beer/test/506/
```
=> correction_history: add threat history

src/search/move_picker.h
Slightly increased node count, because history heuristic updates during search. Net elo gain due to the speedup of pre-calculating scores.
Bench 3271931
```
Elo   | 14.32 +- 9.82 (95%)
LLR   | 2.30 (-2.94, 2.94) [-5.00, 0.00]
```
https://openbench.bunny.beer/test/504/
=> move_picker: pre-score quiet phases

src/movegen/move_generation.h, src/movegen/move_types.h, src/movegen/pawns.h, src/search/move_picker.h, src/search/searcher.h
Closes #172 
```
Elo   | 20.05 +- 6.11 (95%)
LLR   | 2.95 (-2.94, 2.94) [0.00, 2.00]
Games | N: 6904 W: 2148 L: 1750 D: 3006
Penta | [226, 739, 1207, 971, 309]
https://openbench.bunny.beer/test/547/
```
=> movegen: add `MoveNoisy` type | searcher: use `MoveNoisy` in qsearch | move_picker: skip bad noisy moves

src/core/board_defs.h, src/core/move_handling.h, src/evaluation/see_swap.h, src/utils/bit_operations.h
See each commit :)
```
Elo   | 6.16 +- 4.46 (95%)
Games | N: 11048 W: 2873 L: 2677 D: 5498
Penta | [268, 1370, 2126, 1418, 342]
https://openbench.bunny.beer/test/550/
```
=> see_swap: correct lva | correct promotion scores | correct en-pessant score

src/spsa/parameters.h
Applies the tuning from https://openbench.bunny.beer/tune/541/
Bench 1415419
```
Elo   | 25.11 +- 10.33 (95%)
Games | N: 2190 W: 645 L: 487 D: 1058
Penta | [54, 226, 410, 318, 87]
https://openbench.bunny.beer/test/552/
```
=> spsa: apply tuning from `spsa 12-07-25`

src/evaluation/see_swap.h, src/spsa/parameters.h
Previously we had two issues:
1. we returned 0 when no counter attackers. Here we should return the gain of no counter attacks.
2. Promotion score was off - we didn't add the gain of the promoted piece. As the SEE values are off by our tuning I've reset these to primitive values. They'll be adjusted in next spsa tuning.
Bench 1410566
```
Elo   | 5.17 +- 3.90 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
Games | N: 14102 W: 3563 L: 3353 D: 7186
Penta | [362, 1657, 2853, 1767, 412]
https://openbench.bunny.beer/test/596/
```
=> see_swap: fix initial and promotion score

src/evaluation/score.h, src/evaluation/see_swap.h, src/movegen/move_types.h, src/search/move_picker.h, src/search/searcher.h, src/spsa/parameters.h, src/utils/bit_operations.h, tests/src/test_see_swap.cpp
SEE pruning is an attempt at pruning branches by evaluating the worst/best case scenario in a simplified way.
If the SEE score is significantly low then we can assume that the given branch is not worth searching.
This implementation is very similar to our capture score but here we just compute a balance - and quiet moves are also accepted.
Bench 1209330
```
Elo   | 7.16 +- 3.40 (95%)
LLR   | 2.96 (-2.94, 2.94) [0.00, 2.00]
Games | N: 19080 W: 4874 L: 4481 D: 9725
Penta | [510, 2212, 3803, 2405, 610]
https://openbench.bunny.beer/test/613/
```
=> searcher: add see pruning

src/spsa/parameters.h
Apply spsa tuning from:
https://openbench.bunny.beer/tune/621/
Bench 813471
```
Elo   | 35.25 +- 11.95 (95%)
LLR   | 3.00 (-2.94, 2.94) [0.00, 5.00]
Games | N: 1454 W: 427 L: 280 D: 747
Penta | [21, 134, 309, 203, 60]
https://openbench.bunny.beer/test/625/
```
=> spsa: apply parameters from 23-08-25 tuning

src/evaluation/static_evaluation.h, src/evaluation/term_score.h
Meltdown has always had an issue with endgame evaluation. Often engines would flag a position as drawn quite early while Meltdown would still believe that it was a winnable position.
This commit adds piece endgame awareness to our static evaluation. I've ran a few drawn positions where "old Meltdown" would believe they were clearly winning. Now we know that they're clearly drawn.
Also we apply bonus / penalty based on positions that are often won / lost based on remaining material. This is better than simple piece evaluation as we're now context aware as well!
Bench 809831
```
Endgame book:
Elo   | 22.22 +- 8.09 (95%)
Games | N: 1754 W: 421 L: 309 D: 1024
Penta | [9, 134, 474, 256, 4] …
```
=> static_evaluation: add endgame scaling

.gitignore
Not all versions of meson adds this automatically. So ensure we handle that.
Bench 836728
=> git: add 'subprojects' to gitignore
