hansbinderup/meltdown-chess-engine

src/bit_board.h, src/board_defs.h, src/engine/move_handling.h, src/evaluation/evaluator.h, src/evaluation/history_moves.h, src/evaluation/killer_moves.h, src/evaluation/material_scoring.h, src/evaluation/move_scoring.h, src/evaluation/perft.h, src/evaluation/pv_table.h, src/evaluation/repetition.h, src/movement/move_types.h, src/parsing/input_parsing.h, src/uci_handler.h, tests/src/test_move_gen_hashing.cpp, tests/src/test_move_ordering.cpp, tests/src/test_pv_table.cpp
=> Bug fixes, optimizations and some code improvements

src/attack_generation.h, src/board_defs.h, src/engine/tt_hash.h, src/engine/tt_hash_table.h, src/evaluation/evaluator.h, src/evaluation/material_scoring.h, src/evaluation/position_tables.h, src/evaluation/positioning.h, src/helpers/bit_operations.h, src/helpers/debug.h, src/movement/kings.h, src/uci_handler.h, tests/src/test_tt_hash_table.cpp
=> Evaluation improvements, search improvements, hash table improvements

docs/uci_protocol.txt, meson.options, scripts/unit_test.sh, src/evaluation/evaluator.h, tests/meson.build
=> Fix 'debug eval' bug, add uci protocol docs and use 0.0.0-dev as default dev build

.github/workflows/create_release.yml
This workflow will be dispatched to create new releases. An input will contain version and if the release should be a pre-release.
=> workflows: add create_release

.github/workflows/pull_request.yml, meson.build, scripts/build.sh, scripts/ci_build.sh, scripts/create_release.sh, scripts/debug.sh, src/main.cpp, targets/linux-gcc-x86-64-v2.txt, targets/linux-gcc-x86-64-v3.txt, targets/linux-native.txt, targets/meson.build, version/version.h.in
=> meson: add cross compilations

src/evaluation/move_ordering.h
Previously std::stable_sort was used as the sorting algortihm. This adds quite a bit of overhead for sorts of our size.
Instead implement a primitive insertion sort which is also deemed fully deterministic + low runtime overhead.
Test results:
Score of Meltdown Build vs Meltdown v1.1: 113 - 52 - 120  [0.607] 285
...      Meltdown Build playing White: 56 - 25 - 62  [0.608] 143
...      Meltdown Build playing Black: 57 - 27 - 58  [0.606] 142
...      White vs Black: 83 - 82 - 120  [0.502] 285
Elo difference: 75.5 +/- 30.9, LOS: 100.0 %, DrawRatio: 42.1 %
SPRT: llr 2.96 (100.4%), lbound -2.94, ubound 2.94 - H1 was accepted
=> move_ordering: use primitive insertion sort

meson.build, src/bit_board.h, src/engine/move_handling.h, src/evaluation/evaluator.h, src/evaluation/perft.h, src/parsing/input_parsing.h, src/syzygy/syzygy.h, src/uci_handler.h, subprojects/fathom.wrap, targets/linux-gcc-x86-64-v2.txt, targets/linux-gcc-x86-64-v3.txt, targets/linux-native.txt, tests/cute-chess/config.json.example, tests/cute-chess/run-tournament.sh, tests/src/test_move_gen_hashing.cpp, tests/src/test_scoring.cpp, tests/src/test_see_swap.cpp
=> syzygy: add endgame table support

src/bit_board.h, src/engine/move_handling.h, src/evaluation/history_moves.h, src/evaluation/move_ordering.h, src/evaluation/see_swap.h, src/syzygy/syzygy.h
Colour is always known for these calls, so only search for pieces of that colour.
=> move_gen: Implement half-search for `getPieceAtSquare`

src/evaluation/evaluator.h
=> Fix PV line corruption

src/bit_board.h, src/engine/move_handling.h, src/evaluation/history_moves.h, src/evaluation/move_ordering.h, src/evaluation/see_swap.h, src/syzygy/syzygy.h, tests/src/test_history_moves.cpp
=> move_gen: fix half search

README.md
Everyone knows that badges are cool, so let's add some!
NOTE: colors are a primitive attempt of rainbow..
=> readme: add some badges

Makefile, README.md, meson.build
=> Support OpenBench

src/engine/tt_hash_table.h, src/evaluation/evaluator.h, src/uci_handler.h, tests/src/test_tt_hash_table.cpp
[Test results](https://openbench.bunny.beer/test/17/)
=> tt_hash_table: remove generation and improve ttMove ordering

src/evaluation/evaluator.h, src/evaluation/searcher.h, src/time_manager.h, src/uci_handler.h
=> time_manager: initial time manager

src/board_defs.h, src/engine/bench.h, src/evaluation/evaluator.h, src/evaluation/perft.h, src/time_manager.h
```
Elo   | 49.84 +- 30.18 (95%)
SPRT  | 8.0+0.08s Threads=1 Hash=8MB
LLR   | 4.72 (-2.99, 4.55) [0.00, 80.00]
Games | N: 386 W: 166 L: 111 D: 109
Penta | [19, 23, 70, 46, 35]
https://openbench.bunny.beer/test/70/
Elo   | 60.98 +- 38.01 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=64MB
LLR   | 4.62 (-2.99, 4.55) [0.00, 50.00]
Games | N: 236 W: 96 L: 55 D: 85
Penta | [7, 22, 32, 37, 20]
https://openbench.bunny.beer/test/71/
```
=> TimeManager: add soft/hard limit |use system_clock->steady_clock | fix no time input

src/engine/tt_hash_table.h
Previously we would keep incrementing the counter whenever we wrote an entry. This was merely an approximation of how full the table was.
Another, and more efficient, way is to take a random snapshot of the table and check each of those and extract a permill.
The simplest, and most efficient of above, is to take a sample base of 1000 entries as we'll already have the permill as result. Easy :)
Bench 11029400
```
Elo   | -0.35 +- 8.96 (95%)
Conf  | 8.0+0.08s Threads=1 Hash=8MB
Games | N: 2006 W: 694 L: 696 D: 616
Penta | [53, 140, 615, 146, 49]
https://openbench.bunny.beer/test/86/
```
=> tt_hash_table: improve hash full

src/board_defs.h, src/engine/tt_hash_table.h, src/evaluation/score.h, src/evaluation/searcher.h, tests/src/test_tt_hash_table.cpp
```
Elo   | 68.71 +- 5.59 (95%)
Conf  | 8.0+0.08s Threads=1 Hash=128MB
Games | N: 10004 W: 4357 L: 2404 D: 3243
Penta | [280, 736, 1669, 1385, 932]
https://openbench.bunny.beer/test/115/
```
=> tt_hash_table: improve read and write

src/evaluation/searcher.h
This commit adds a search stack for the searchers. Previously we stored a local hash copy + "new board" when performing the search recursion.
It is beneficial to actually store all the positions we've been through during the search. This means that we can, in theory, iterate the stack and get a better understanding on how the current search is performing.
Furthermore it should improve the cache as we no longer allocate the temporary hash and board on the stack.
Bench 8741465
```
Elo   | 2.53 +- 8.02 (95%)
LLR   | 0.67 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 2330 W: 763 L: 746 D: 821
Penta | [48, 172, 711, 183, 51]
https://openbench.bunny.beer/test/145/
```
=> searcher: add search stack

src/board_defs.h, src/time_manager.h, src/uci_handler.h
This should significantly improve our 40/15 rating on CCRL as well - proper time management for that format :muscle:
=> time_manager: strong duration types | uci option for move overhead | improve moves to go time handling

src/search/searcher.h
The previous PVS was copied from an old thread where some hacks were applied.
This is a more readable, less hacky and better performing way of handling PVS.
Bench 3083329
Test shows little to no difference (see LLR):
```
Elo   | -1.23 +- 6.88 (95%)
LLR   | 0.13 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 4526 W: 1176 L: 1192 D: 2158
Penta | [121, 563, 915, 539, 125]
https://openbench.bunny.beer/test/307/
```
=> searcher: clean up PVS

src/search/searcher.h
Our previous qsearch implementation was rather stupid. It would just play through all captures and check for static evals.
Problem is that we can not just count on static eval. The board can be a draw, check mate etc. So in case of draws we might actually think that the board is winning when it's in fact not.
This commit refactors how we handle beta cut offs - they need to be propagated all the way from qsearch to root.
Bench 2338571
```
Elo   | 23.12 +- 13.87 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 10.00]
Games | N: 1430 W: 445 L: 350 D: 635
Penta | [48, 155, 242, 194, 76]
https://openbench.bunny.beer/test/342/
```
=> searcher: make beta static eval aware

meson.build, src/evaluation/evaluator.h, src/evaluation/score.h, src/interface/outputs.h, src/interface/uci_handler.h, src/main.cpp
Absolutely not necessary, but why not :)
```
Elo   | -1.25 +- 7.15 (95%)
LLR   | 0.11 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 4180 W: 1110 L: 1125 D: 1945
Penta | [115, 500, 883, 469, 123]
https://openbench.bunny.beer/test/349/
```
=> interface: add pretty printing

scripts/build.sh, src/interface/outputs.h, src/movegen/kings.h, src/movegen/knights.h, src/search/searcher.h
see each commit for details :)
=> Bunch of minor fixes

src/evaluation/evaluator.h, src/interface/outputs.h, src/interface/uci_handler.h, src/search/searcher.h, src/syzygy/syzygy.h
Privously the syzygy probe had a few flaws:
1. probeWdl -> never actually worked as the 50move rule would apply as the input is bool and not a number, sigh
2. we would blindly return the results of the WDL -> no pv line and no beta alpha awareness
- syzygy is not shortest line aware
- syzygy is not pv line aware
3. we would store a static result of the initial probe and just expect this to be the outcome of the position. This is partially correct, but it leads to nasty pv lines and potential draw scenarios where we could otherwise have won.
4. blessed win/loss would also be considered a win/loss. Well, that requires that the opponent makes a mistake and we can not afford to make that assumption.
Now we treat the syzygy probe as a table probe (similar to TT) and will only return early if …
=> syzygy: less aggressive cutoffs

src/core/transposition.h, src/search/move_picker.h, src/search/pv_table.h, src/search/search_tables.h, src/search/searcher.h, tests/src/test_pv_table.cpp, tests/src/test_transposition.cpp
```
Elo   | -0.11 +- 2.66 (95%)
SPRT  | 8.0+0.08s Threads=1 Hash=128MB
LLR   | 2.96 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 30612 W: 7549 L: 7559 D: 15504
Penta | [874, 3673, 6182, 3743, 834]
https://openbench.bunny.beer/test/396/
```
=> transposition: add tt pv | remove pv move picking

src/core/transposition.h
Use multiply-shift hashing instead of modulo for faster index computation
This improves performance over `%` at the cost of slight bias when the table size is not a power of two.
NOTE: this works as long as the table is smaller than 2^64 which should never happen in real life x) (our tables are limited from UCI to an actual realistic value)
Bench 2881777
```
Elo   | 10.77 +- 6.43 (95%)
LLR   | 2.95 (-2.94, 2.94) [0.00, 5.00]
Games | N: 5582 W: 1534 L: 1361 D: 2687
Penta | [149, 659, 1049, 738, 196]
https://openbench.bunny.beer/test/533/
```
=> transposition: use multiply-shift hashing for index
